version: "3.7"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.18.0/24
volumes:
    sonarqube_conf:
      driver: local
    sonarqube_data:
      driver: local
    sonarqube_extensions:
      driver: local
    sonarqube_bundled-plugins:
      driver: local

services:
  sonar:
          build:
              context: ./
              dockerfile: dockerfile-sonar
          image: sonar
          networks:
              default:
                  ipv4_address: 172.18.18.14
          ports:
              - "8081:9000"
              - "8082:9002"
          volumes:
              - sonarqube_conf:/opt/sonarqube/conf
              - sonarqube_data:/opt/sonarqube/data
              - sonarqube_extensions:/opt/sonarqube/extensions
              - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
